spring:
  application:
    name: TaskManagement

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings.trace: false
#      settings.web-allow-others: false
#
#  datasource:
#    url: jdbc:h2:file:/data/taskManagement
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#    jpa:
#      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#      defer-datasource-initialization: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
#    username: taskManagement
#    password: taskManagement
#    default_schema: taskManagement
#    driver-class-name: org.postgresql.Driver
#    dialect: org.hibernate.dialect.PostgreSQLDialect